name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  SHA: ${{ github.event.pull_request.head.sha || github.event.after }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.SHA }}
          
      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2.4.1

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.revision=${{ env.SHA }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          load: ${{ github.event_name == 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          attests: type=sbom,generator=christiandupuis299/buildkit-syft-scanner:files
          provenance: true

      - name: Create CVE report
        uses: docker/scout-action@ca09af31fdb99995a36608d63aba7b5e4f66709a
        with:
          command: cves
          image: ${{ steps.meta.outputs.tags }}
          args: '--output image.sarif.json --format sarif' 
          user: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          registry_user: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: image.sarif.json     
      
      - name: Scan Vulnerabilities
        run: |
          cat image.sarif.json | \
          jq '{ critical: [select(.runs[-1].results[].message.text  | contains(": CRITICAL"))] | length, high: [select(.runs[-1].results[].message.text  | contains(": HIGH"))] | length, medium: [select(.runs[-1].results[].message.text  | contains(": MEDIUM"))] | length, low: [select(.runs[-1].results[].message.text  | contains(": LOW"))] | length }' > \
          vulnerabilities.json
      
      - name: GH Actions Summary
        shell: python
        run: |
          import json
          import os


          css_critical_color = "ab1a1a"
          css_high_color = "ce5019"
          css_medium_color = "d68000"
          css_low_color = "88879e"

          with open("vulnerabilities.json") as fh:
              vulnerabilities = json.load(fh)

          critical = vulnerabilities.get("critical", 0)
          high = vulnerabilities.get("high", 0)
          medium = vulnerabilities.get("medium", 0)
          low = vulnerabilities.get("low", 0)

          # Shields.io Badges
          SHIELDSIO_BADGES = f"![Critical](https://img.shields.io/badge/Critical-{critical}-{css_critical_color}.svg) \
          ![High](https://img.shields.io/badge/High-{high}-{css_high_color}.svg) \
          ![Medium](https://img.shields.io/badge/Medium-{medium}-{css_medium_color}.svg) \
          ![Low](https://img.shields.io/badge/Low-{low}-{css_low_color}.svg)"

          with open(os.environ["GITHUB_STEP_SUMMARY"], "a") as fh:
              print("# Vulnerabilities", file=fh)
              print(SHIELDSIO_BADGES, file=fh)

       
          
          
          
          
